### ISSUE TITLE
StaleElementReferenceException when constructing TextField after webform ajax postback.

### ISSUE THREAD

**Issue by JonBons** [Bumblebee/Bumblebee#18]
Block property:

``` vb
Public ReadOnly Property Name As TextField(Of InformationTab)
    Get
        Return New TextField(Of InformationTab)(Me, By.Id(Me.Base & "txtName"))
    End Get
End Property
```

``` vb
.ContactType("Organization").Click(Of InformationTab).Pause(3000)
```

The Click call causes an ajax postback (I'm working on detecting when that finishes) and after that I call:

``` vb
.Name.EnterText(sCusID)
```

which results in the exception being thrown because the page has reflowed.

Full page: https://gist.github.com/JonBons/577f4233a76ffb7a6f75
(You will see that I fixed it for parts of the page by scoping back to the ContactPage but that has a bad smell)

**Comment by JonBons** [comment]
@toddmeinershagen I don't think I'll be able to provide a static page or a URL (internal site on admin pages) to reproduce this in a timely manor but I can test the changes in that PR against this issue.

**Comment by toddmeinershagen** [comment]
@JonBons - what browser are you using when you encounter the stale element issue?  (I am assuming that it is IE in a lower version.)

**Comment by JonBons** [comment]
@toddmeinershagen Chrome

**Comment by toddmeinershagen** [comment]
@JonBons We have released an alpha version of 2.0.0 for Bumblebee.  This should address this issue.  Please take a look and give us feedback.

**Comment by toddmeinershagen** [comment]
@JonBons @drusellers We have added the ability to lazy load Blocks in the v2 alpha release, which you should check out to see if it addresses your current issue.  Let us know if this clears things up.

We are also planning to modify Elements to make them lazy loading as well.

**Note** - these changes will be breaking changes, since we no longer will support passing an IWebElement tag to these constructors.  Hence, this will be released as v2.

**Comment by toddmeinershagen** [comment]
I am assuming since we have not received any feedback that this issue is resolved with the v2 framework.
