### ISSUE TITLE
Sending additional header to browser

### ISSUE THREAD

**Issue by tarurar** [Bumblebee/Bumblebee#88]
It comes very useful when we a talking about authentication options. For example, I have a site with forms based authentication.
Is it possible to send additional header to the browser with the help of Bumblebee? May be you know another way?

**Comment by toddmeinershagen** [comment]
Interestingly, the Selenium team has taken the position not to support anything that a user wouldn't be able to do.  So, in this case, they do not have an API for setting request headers.  Since we are a page abstraction on top of Selenium, we too do not support this.

Instead, for your case, you could just navigate to the login form and actually enter the username/password to login.  As you move forward through the website, a forms authentication cookie should be set that keeps you logged in, like any other browser user.

Another option is to set up headers as part of the underlying Driver.  I believe that Firefox and GhostDriver both support this behavior.

Hope it helps.
