### ISSUE TITLE
Interacting with framesets

### ISSUE THREAD

**Issue by dawsonjk** [Bumblebee/Bumblebee#92]
I'd like to be able to interact with elements within an iframe > frameset > frame > body.

**Comment by CrunPud** [comment]
I had to deal with framesets recently.  In my case, the popup I was dealing with had no body element, which required a different workaround, so my hierarchy went  frameset > frame > body.  All I did was create an inlineframe, and then did an override on the Tag.  Code looked like this.

```c#
public override IWebElement Tag
{
    get
    {
         return Session.Driver.SwitchTo()
             		.Frame(Session.Driver.FindElement(By.TagName("frameset")))
                        .SwitchTo().Frame(Session.Driver.FindElement(Specification))
                        .FindElement(By.TagName("body"));
    }
}
```
Since you have an extra iframe, you could do the same thing but with one extra line

**Comment by toddmeinershagen** [comment]
@dawsonjk - Did the response from @CrunPud answer your question.  (need feedback to close the issue.)

**Comment by toddmeinershagen** [comment]
@dawsonjk I haven't heard back about this issue since my response to you in 2018.  I am going to close it for now, but feel free to add a new issue if you are still having problems and refer to this original issue.
