### ISSUE TITLE
How to Select a dropdown using Bumblebee framework?

### ISSUE THREAD

**Issue by ashokkumarg** [Bumblebee/Bumblebee#93]
Using Bumblebee framework how to select a dropdown? ISelectbox, ISelectable objects are available but how to make use of it?

**Comment by toddmeinershagen** [comment]
If you have the following html:

```html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta charset="utf-8"/>
		<title>Single Select</title>
	</head>
	<body>
		<div align="center">
			<select id="SelectBox">
				<option value="1">mushrooms</option>
				<option value="2">green peppers</option>
				<option value="3">onions</option>
				<option value="4">tomatoes</option>
				<option value="5">olives</option>
			</select>
		</div>
	</body>
</html>
```

You can select this select box from your page using the following syntax:

```csharp
public class SelectPage : WebPage
{
	public SelectPage(Session session) : base(session)
	{
	}

	public ISelectBox<SelectPage> Toppings
	{
		get { return new SelectBox<SelectPage>(this, By.Id("SelectBox")); }
	}
}
```

If you still have issues, let me know.  Also - which version of the framework are you using?

**Comment by ashokkumarg** [comment]
I use Bumblebee 1.2.0.0. I will check with the code revert you.

**Comment by tarurar** [comment]
@toddmeinershagen , any updates?

**Comment by toddmeinershagen** [comment]
@tarurar @ashokkumarg - The ISelectBox has a property, Options, that is an IEnumerable<IOption>.  Each option has a Text and Selected property and can be clicked.  
If you want to select an element by its text, you must use LINQ to Objects syntax like so:

```csharp
var page = new SelectPage(session);
page.Toppings
  .Options
  .Where(o => o.Text == "mushrooms")
  .Click();
```

With the 1.2.0.0 framework, there is no option for selecting elements by their value.  That makes sense since no end user would be aware of this value either.  However, I believe that we included this in the 2.0 version of the framework.

Does that answer the initial question?

**Comment by tarurar** [comment]
"Yes" for me )), thank you.

**Comment by ashokkumarg** [comment]
Yes, that make sense and moved to the new version.
