### ISSUE TITLE
Switching to newly opened tab

### ISSUE THREAD

**Issue by tarurar** [Bumblebee/Bumblebee#98]
Is it achievable?
Once I execute click on a link new tab opens, but the context still remains on the previous tab. How can I switch to the new tab?

**Comment by toddmeinershagen** [comment]
It's possible, but it will probably be dependent on the components framework you are using for rendering the tabs.  Since, this is not a standard for HTML elements, we couldn't create a default implementation.

I believe that the Clickable<T>() takes in an IBlock which can be anything you want to return when it is called.  So, normally, you would return the parent block (this), but you could return anything you want.

For instance, instead of:

```csharp
public IClickable<ClickablePage> Tab1
{
	get { return new Clickable<ClickablePage>(this, By.Id("tab1")); }
}
```

You could do the following:

```csharp
public IClickable<Tab1Block> Tab1
{
	var tab1Block = this.FindElement(By.Id("tab1Block"));
	get { return new Clickable<Tab1Block>(tab1Block, By.Id("tab1")); }
}
```

**Comment by toddmeinershagen** [comment]
@tarurar - did my response help?  (need feedback to know if we can close this issue.)

**Comment by tarurar** [comment]
Yes it helped, thank you.

**Comment by toddmeinershagen** [comment]
@tarurar - Thanks, I'll close this issue now.
