### ISSUE TITLE
.Net Core Support

### ISSUE THREAD

**Issue by CrunPud** [Bumblebee/Bumblebee#99]
Are there any plans to port this to .Net Core?
It looks like the only issues might be the PlaySound method in the Debugging Extension which uses System.Media.

**Comment by toddmeinershagen** [comment]
Actually - we were waiting for the Selenium team to update their Selenium.WebDriver project to support .NET core.  It looks like that may have happened at this point.

And you are right that the playing of the sound in the Debugging.cs file (```PlaySound<T>()```) is the only non-supported feature.  I am not sure how widely used that functionality is.  It looks like there might be some options to use the [SoundPlayer class](https://msdn.microsoft.com/en-us/library/system.media.soundplayer(v=vs.80).aspx) that has been added to the .NET Core 2.0 framework.

There is some work that needs to be done in order to get the build to support multiple targets.  I'll keep this issue updated on our progress.  

In the meantime, if you would like to issue a pull request, we would be open to reviewing/merging.

**Comment by toddmeinershagen** [comment]
I found a [beep.wav](https://www.soundjay.com/button/beep-08b.wav) file that we could embed in our assembly.  It can be played by doing the following, which I think is available in .NET Core 2.0.

```csharp
var assembly = System.Reflection.Assembly.GetExecutingAssembly();
var player = new System.Media.SoundPlayer(assembly.GetManifestResourceStream("Bumblebee.beep.wav"));
player.Play();
```

**Comment by CrunPud** [comment]
I'll try and get a pull request put together tonight.

**Comment by jbiesta** [comment]
@CrunPud Do you have any update on looking at a PR for the core support? We're wondering whether to do the same!

**Comment by CrunPud** [comment]
I have been busy starting a new job and moving to a new state, but I was able to spend a couple hours on setting up the single project to target multiple frameworks.  I am running into an issue experienced by some people in this [thread](https://github.com/dotnet/sdk/issues/1321) where I get an error insisting that I add net40 to the targeted frameworks.  It goes away if I do as the error suggests, but then  have issues with the InternalsVisibleToAttribute in the AssemblyInfo file.  I'll spend more time on it tomorrow if I have the chance.

**Comment by toddmeinershagen** [comment]
I have a pull request put together to address this issue -- just waiting for the tests to pass on AppVeyor and then I will merge and release to nuget the 1.3 version.

**Comment by cdroulers** [comment]
Hey Todd, I'll see what I can do when I have time soon!

**Comment by cdroulers** [comment]
PR is here: https://github.com/Bumblebee/Bumblebee.KendoUI/pull/3
